### ISSUE TITLE
SNAPSHOTS

### ISSUE THREAD

**Issue by smeenakshi68** [smeenakshi68/CollegeManagementSystem#1]
SCREEN SHOTS AND HOW TO USE WEBSITE

1   Overview
• Build a web portal/website using 3 tier client server architecture and utilize technologies like JSP, Java, MySQL, JDBC, Application Server,  
• Enable various academic and nonacademic activities for students, parents, admin to access/view information based upon their roles

2   Application Features
2.1 Home Page
• Contain search bar
• Sign in 
• Menu bar for various other page sites

![image](https://cloud.githubusercontent.com/assets/13386466/10328859/80c86c7e-6c87-11e5-980e-6beb9957bf7e.png)

2.2 Search Functionality
Search Entire Website

![image](https://cloud.githubusercontent.com/assets/13386466/10328876/d8cbdbae-6c87-11e5-8785-41365f59715f.png)
![image](https://cloud.githubusercontent.com/assets/13386466/10328888/090f8dba-6c88-11e5-910d-12d974737336.png)
![image](https://cloud.githubusercontent.com/assets/13386466/10328889/0faa43f4-6c88-11e5-89ac-3550c518b37b.png)
![image](https://cloud.githubusercontent.com/assets/13386466/10328893/172d9068-6c88-11e5-9aea-faac87ac8b2a.png)
![image](https://cloud.githubusercontent.com/assets/13386466/10328896/1e54d4fa-6c88-11e5-9ae4-d44e3b7ea0b4.png)
![image](https://cloud.githubusercontent.com/assets/13386466/10328900/25e75206-6c88-11e5-8cf0-5d879e43f74f.png)
Edit Record 
![image](https://cloud.githubusercontent.com/assets/13386466/10328908/315255e6-6c88-11e5-9557-0a53291347d1.png)

Student Search & View their details
![image](https://cloud.githubusercontent.com/assets/13386466/10328918/43e62c8c-6c88-11e5-8759-c9f93c41436c.png)

![image](https://cloud.githubusercontent.com/assets/13386466/10328920/4913c3ea-6c88-11e5-88c7-4215da783509.png)

![image](https://cloud.githubusercontent.com/assets/13386466/10328923/52e961ea-6c88-11e5-89f1-f518d8516dcd.png)

Generate Report

![image](https://cloud.githubusercontent.com/assets/13386466/10328934/66a7c5dc-6c88-11e5-8652-3061d8cc8e69.png)
![image](https://cloud.githubusercontent.com/assets/13386466/10328936/6ec26a06-6c88-11e5-9b57-187e94236752.png)

Open Report in Excel
![image](https://cloud.githubusercontent.com/assets/13386466/10328944/7c0e91da-6c88-11e5-98f7-61abb8ce1f4a.png)

2.4.3   Student View and Screen
![image](https://cloud.githubusercontent.com/assets/13386466/10328958/92ab441a-6c88-11e5-8df6-c096a50288a4.png)

![image](https://cloud.githubusercontent.com/assets/13386466/10328962/9897e022-6c88-11e5-92db-08dcad8cf424.png)

![image](https://cloud.githubusercontent.com/assets/13386466/10328970/9f7c4a72-6c88-11e5-83cf-b32bc46f2eac.png)

![image](https://cloud.githubusercontent.com/assets/13386466/10328972/a640cef0-6c88-11e5-8c76-80cabe1b6d8a.png)

![image](https://cloud.githubusercontent.com/assets/13386466/10328976/b162a178-6c88-11e5-9a5d-618763a54da7.png)

```
   Faculty Access & View Student Details
```

![image](https://cloud.githubusercontent.com/assets/13386466/10328984/c5e3305e-6c88-11e5-8ef7-15ef23336332.png)

![image](https://cloud.githubusercontent.com/assets/13386466/10328989/d173ec6a-6c88-11e5-8779-4be2c2ca8b4f.png)

![image](https://cloud.githubusercontent.com/assets/13386466/10328993/da1fe238-6c88-11e5-846c-add450526d0e.png)

3   Application UI  

Home Screen Slider
![image](https://cloud.githubusercontent.com/assets/13386466/10329002/e818055a-6c88-11e5-923a-8e43321ad58d.png)

![image](https://cloud.githubusercontent.com/assets/13386466/10329005/f30960d0-6c88-11e5-9c68-8af0698a9038.png)

![image](https://cloud.githubusercontent.com/assets/13386466/10329010/01179250-6c89-11e5-9049-a4a5514c54c2.png)

![image](https://cloud.githubusercontent.com/assets/13386466/10329013/0c702f72-6c89-11e5-8108-4f0643a790e3.png)

![image](https://cloud.githubusercontent.com/assets/13386466/10329017/112b5ffa-6c89-11e5-9766-4c2dbc0b5f8d.png)

![image](https://cloud.githubusercontent.com/assets/13386466/10329023/1bf6a3d6-6c89-11e5-8266-3f7bd6284825.png)

**Comment by prakashv065** [comment]
Hi i have gone through your application. it is really good work that you did. But i am not able to get the db file to make the application run. can you drop me the file to my email id :prakashv065@gmail.com.
